# Your Token
token: ""
# Interval to change text
interval: 10
# Status / Bio
mode: "Status"
message:
  - "ğŸ§¡ğŸ¤ğŸ§¡ğŸ¤ğŸ§¡ğŸ¤ğŸ§¡ğŸ¤"
  - "ğŸ¤ğŸ§¡ğŸ¤ğŸ¤ğŸ§¡ğŸ¤ğŸ¤ğŸ§¡"
  - "â° %m:%d"
  - "â° %Hæ™‚%Mç§’"
  - "â²ï¸ %Sç§’"
  - "ã‚„ã‚Šã¾ã™ã­ã‡ï¼"
# Example: "Year: %Y Month: %b Date: %d Hour: %H Minutes: %M Second: %S"
# Weekday short version %a
# Weekday full version  %A
# Weekday as a number   %w
# Day of month          %d
# Month Name short ver  %d
# Month Name full ver   %b
# Month as a number     %m
# Year short version    %y
# Year full version     %Y
# Hour (00-23)          %H
# Hour (00-11)          %I
# AM/PM                 %p
# Minute                %M
# Second                %S